name: 'dynamosync'
version: '1.0.0'
config-version: 2

profile: 'dynamosync'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dynamosync:
    # Configure your models here
    staging:
      +materialized: view
      +schema: staging
    
    intermediate:
      +materialized: view
      +schema: intermediate
    
    mart:
      +materialized: table
      +schema: mart

seeds:
  dynamosync:
    +schema: seed_data

# Package dependencies
packages:
  - package: dbt-labs/dbt_utils
    version: ">=1.0.0,<2.0.0"